version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
#      - redis

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=template

#  redis:
#    image: redis
#    command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - redis_data:/data

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
#  redis_data:
