version: '3.7'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 80:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
#      - redis

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=template

#  redis:
#    image: redis
#    command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - redis_data:/data

volumes:
  postgres_data:
#  redis_data:
